### ISSUE TITLE
initiate the project with typescript

### ISSUE THREAD

**Issue by Ryan-Willpower** [Ryan-Willpower/2019-blog#1]
Add Typescript and remove unnecessary code

**Comment by 0pdd** [comment]
@Ryan-Willpower the puzzle [#4](https://github.com/Ryan-Willpower/2019-blog/issues/4) is still not solved.

**Comment by Ryan-Willpower** [comment]
done via 8ba2998f7f76625a984a8564d164c768537fa643

**Comment by 0pdd** [comment]
@Ryan-Willpower 2 puzzles [#4](https://github.com/Ryan-Willpower/2019-blog/issues/4), [#9](https://github.com/Ryan-Willpower/2019-blog/issues/9) are still not solved.

**Comment by 0pdd** [comment]
@Ryan-Willpower the puzzle [#4](https://github.com/Ryan-Willpower/2019-blog/issues/4) is still not solved; solved: [#9](https://github.com/Ryan-Willpower/2019-blog/issues/9).
